### ISSUE TITLE
SC_ユーザ情報閲覧（詳細）

### ISSUE THREAD

**Issue by dmanabe** [yyamnk/sample_admin_roles#2]
◆レイアウト不正
①名前（英）に長い文字列が入る場合、改行されない。
＞名前（ja）は長くても改行される。

◆辞書ファイル定義
①名前　→　氏名
②Name　→　氏名（英）
③Department name ja　→　所属
④Grade name　→　学年

**Comment by yyamnk** [comment]
> 名前（英）に長い文字列が入る場合、改行されない。

スペースがあれば改行されるので, 良いことにしましょう.
