### ISSUE TITLE
SC_管理者メニュー

### ISSUE THREAD

**Issue by dmanabe** [yyamnk/sample_admin_roles#8]
◆画面遷移
①管理者メニューに入ると、ログアウトしないと利用者メニューに遷移できない。

◆ユーザ情報
①Nameに長い文字列が入っても改行されない。

**Comment by yyamnk** [comment]
> ◆ユーザ情報
> ①Nameに長い文字列が入っても改行されない。

スペースがあれば改行されるので, 良いことにしましょう.
